const mongoose = require('mongoose');

const storeThemeSchema = new mongoose.Schema({
    storeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Store', required: true, unique: true, index: true },
    themePreset: { type: String, enum: ['minimal', 'luxury', 'bold', 'fashion', 'electronics', 'beauty', 'modern', 'classic'], default: 'modern' },
    primaryColor: { type: String, default: '#0a4019' },
    secondaryColor: { type: String, default: '#f5f3f0' },
    accentColor: { type: String, default: '#2563EB' },
    buttonColor: { type: String, default: '#0a4019' },
    buttonTextColor: { type: String, default: '#FFFFFF' },
    textColor: { type: String, default: '#1a1a1a' },
    mutedTextColor: { type: String, default: '#64748B' },
    backgroundColor: { type: String, default: '#ffffff' },
    surfaceColor: { type: String, default: '#FFFFFF' },
    borderColor: { type: String, default: '#E2E8F0' },
    saleColor: { type: String, default: '#DC2626' },
    successColor: { type: String, default: '#16A34A' },
    warningColor: { type: String, default: '#F59E0B' },
    errorColor: { type: String, default: '#DC2626' },
    fontStyle: { type: String, default: 'system' },
    headingFontStyle: { type: String, default: 'system' },
    baseFontSize: { type: String, default: '16px' },
    headingScale: { type: String, default: 'balanced' },
    bodyLineHeight: { type: String, default: '1.6' },
    headingLineHeight: { type: String, default: '1.2' },
    letterSpacing: { type: String, default: 'normal' },
    borderRadius: { type: Number, default: 8 },
    cardStyle: { type: String, default: 'flat' },
    buttonStyle: { type: String, default: 'solid' },
    layoutDensity: { type: String, enum: ['compact', 'comfortable', 'spacious'], default: 'comfortable' },
    maxContentWidth: { type: String, default: '1320px' },
    pageWidthMode: { type: String, default: 'boxed' },
    sectionSpacing: { type: String, default: 'medium' },
    containerPadding: { type: String, default: '24px' },
    gridGap: { type: String, default: '24px' },
    globalRadius: { type: String, default: 'medium' },
    buttonRadius: { type: String, default: 'medium' },
    cardRadius: { type: String, default: 'large' },
    imageRadius: { type: String, default: 'medium' },
    inputRadius: { type: String, default: 'medium' },
    badgeRadius: { type: String, default: 'pill' },
    cardShadow: { type: String, default: 'soft' },
    buttonShadow: { type: String, default: 'none' },
    headerShadow: { type: String, default: 'subtle' },
    hoverEffect: { type: String, default: 'lift' },
    animationLevel: { type: String, default: 'subtle' },
    customBrandingStatus: { type: String, enum: ['disabled', 'enabled'], default: 'enabled' }
}, { timestamps: true });

module.exports = mongoose.models.StoreTheme || mongoose.model('StoreTheme', storeThemeSchema);
